### ISSUE TITLE
Lack of consistency on ``skip-install`` option

### ISSUE THREAD

**Issue by germa89** [pyansys/actions#137]
Some actions has ``skip-install`` which depending on the action can do just the ``pip install`` (i.e. ``doc-build`` action) or also the checkout, python install and project install (i.e. ``check-license`` action).

We should probably be consistent with its usage.

**Comment by jorgepiloto** [comment]
There reason for this is that some projects use Sphinx but they are not Python libraries. Therefore, installing a library is not required because there is no library. However, Sphinx is still required to be installed together with any additional documentation requirements. Same applies for the license checking action.
