### ISSUE TITLE
Add Depreciation warning/page for very old version of docs.

### ISSUE THREAD

**Issue by Revathyvenugopal162** [pyansys/actions#80]
### 📝 Description of the feature

Add the label depreciated/ add a depreciated pages for the very old versions of the version releases.

### 💡 Steps for implementing the feature

This needs to be added through the versions.json

### 🔗 Useful links and references

 Adding numpy https://numpy.org/doc/1.14/index.html for ref.

**Comment by RobPasMue** [comment]
Interesting... This would imply supporting many more versions than we do right now (we are only intending to support three). Do we still want to put the deprecated message for those three?

BTW, this would imply that when a new version is released, the old documentation versions should also be regenerated to include this deprecation message... I am not a huge fan of this idea but I do see the benefits. Let me investigate a little bit...

**Comment by RobPasMue** [comment]
So it looks like they run an ``update.py`` script after their documentation is committed. This script file is the one that takes responsibility for updating the old docs and adding the warning message. We could have something similar. What do you think @jorgepiloto 

Link to reference: https://github.com/numpy/doc/blob/main/update.py

Now, the fun part... it also implies playing around with JavaScript:
* https://github.com/numpy/doc/blob/main/_static/versionwarning.js_t
* https://github.com/numpy/doc/blob/main/_static/versionwarning.js

You basically have a template, which you edit when the docs are released so that it generates the stable version of the file. This file is then published with the docs. 

The PR in which they did this is the following one: https://github.com/numpy/doc/pull/7 if I am not mistaken.

**Comment by jorgepiloto** [comment]
I bet I've seem this feature in the pydata-sphinx-theme. It should be a matter of adding something to the `versions.json` I think. Let me check.

**Comment by jorgepiloto** [comment]
Here it is. It is called "announcements": https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/announcements.html

**Comment by jorgepiloto** [comment]
However, it looks like you need to modify the `conf.py` for this... It is not going to be trivial to implement for the multi-version documentation.

**Comment by RobPasMue** [comment]
Interesting... Yeah, that would imply regenerating the docs for all previous versions... I bet that's why Numpy went with this other approach

**Comment by jorgepiloto** [comment]
I think we can go with the NumPy approach. We could play with the `version_mapper.py` script to add the script to the different `release/X.Y` except the latest stable and development. I bet we can reuse some of the logic in their `update.py`.

**Comment by jorgepiloto** [comment]
Well... I just better check and it looks it may be possible to play a bit with our `conf.py`files. Let me investigate a bit more.

**Comment by jorgepiloto** [comment]
Let us coordinate in private. I just made some tests locally and this should be straight to implement for us. Sorry for the mess.
